using UnityEngine;
using UnityEngine.XR.Interaction.Toolkit;
using System.Collections;

public class LevierScript : MonoBehaviour
{
    public AudioSource soundbutton;
    public GameObject targetObject; // Le GameObject que vous voulez d√©placer (votre vaisseau)
    public float moveSpeed = 3f;    // Vitesse de d√©placement
    public RedButton redButton; // R√©f√©rence au script RedButton
    public AudioSource VoixTrigger;


    private UnityEngine.XR.Interaction.Toolkit.Interactables.XRGrabInteractable grabInteractable;
    private bool isMoving = false;  // D√©termine si le vaisseau doit bouger ou non
    public bool estActiver { get { return isMoving; } private set { isMoving = value; } }

    private void Start()
    {
        grabInteractable = GetComponent<UnityEngine.XR.Interaction.Toolkit.Interactables.XRGrabInteractable>();
    
        if (grabInteractable != null)
        {
            grabInteractable.selectEntered.AddListener(OnButtonPressed);
            grabInteractable.hoverEntered.AddListener(OnHoverEntered);
        }
        else
        {
            Debug.LogError("‚ö†Ô∏è XRGrabInteractable manquant sur le levier !");
        }
    }

    private void Update()
    {
        // Si le vaisseau doit bouger, on le d√©place
        if (isMoving)
        {
            targetObject.transform.Translate(Vector3.forward * moveSpeed * Time.deltaTime);
        }
    }

    private void OnButtonPressed(SelectEnterEventArgs args)
    {
        if(redButton != null && !redButton.isPressed)
        {
            VoixTrigger.Play();
            Debug.Log("üî¥ Le bouton rouge n'est pas encore press√© ! VoixTrigger launch");
            return;
        }
        Debug.Log("üü¢ Levier Saisi, le vaisseau d√©marre...");

        // üîä Lancer le son si la source audio est d√©finie
        if (soundbutton != null)
        {
            soundbutton.Play();
        }
        else
        {
            Debug.LogWarning("üîá Aucun soundbutton assign√© !");
        }

        // Commencer √† d√©placer le vaisseau
        isMoving = true;
    }

    private void OnHoverEntered(HoverEnterEventArgs args)
    {
        // Vous pouvez ajouter des effets de survol ici
        Debug.Log("üü° Hover sur le levier !");
    }
}