using UnityEngine;
using UnityEngine.UI;

public class CheckMissions : MonoBehaviour{
    public Toggle monCheckMark1;
    public Toggle monCheckMark2;
    public Toggle monCheckMark3;
    public EquiperCasqueVR scriptCasqueVR; 
    public LevierScript scriptLevier;
    public AudioSource terminer;

    void Start()
    {
        if (monCheckMark1 != null)
        {
            monCheckMark1.isOn=false;
        }
        if (monCheckMark2 != null)
        {
            monCheckMark2.isOn=false;
        }
        if (monCheckMark3 != null)
        {
            monCheckMark3.isOn=false;
        }
    }

    void Update()
    {
        if (scriptCasqueVR != null)
        {
            if (scriptCasqueVR.AEteEquipe)
            {
                Debug.Log("Le casque a √©t√© √©quip√© !");
                if (monCheckMark1 != null)
                {
                    monCheckMark1.isOn=true;
                }
            }

            if (scriptCasqueVR.AEteRepose)
            {
                Debug.Log("Le casque a √©t√© repos√© !");
                if (monCheckMark2 != null)
                {
                    monCheckMark2.isOn=true;
                }
            }
            if(scriptLevier.estActiver)
            {
                Debug.Log("Le vaisseau a d√©marr√© !");
                if (monCheckMark3 != null)
                {
                    monCheckMark3.isOn=true;
                }
            }else if(scriptLevier.estActiver&&scriptCasqueVR.AEteEquipe&&scriptCasqueVR.AEteRepose)
            {
                Debug.Log("Mission termin√©e !");
                if (terminer != null)
                {
                    terminer.Play();
                }
                else
                {
                    Debug.LogWarning("üîá Aucun son assign√© pour la mission termin√©e !");
                }
            } 
        }
    }
}